### ISSUE TITLE
Add package selection argument that is union of --packages-up-to and --packages-above

### ISSUE THREAD

**Issue by brawner** [colcon/colcon-package-selection#29]
When making changes to a package that has a lot of dependent packages, it would be great to run builds/tests on all packages that depend on it. However, you still need to build all the packages up to that target package.

If I run the following, the result is the intersection of the two (rclcpp).
```
colcon build --packages-up-to rclcpp --packages-above rclcpp
``` 

In particular for CI purposes, it would be great for there to be an option that is the union of the two. Basically the equivalent of running following sequentially but as a single command:
```
colcon build --packages-up-to rclcpp
colcon build --packages-above rclcpp
```

**Comment by dirk-thomas** [comment]
> When making changes to a package that has a lot of dependent packages, it would be great to run builds/tests on all packages that depend on it. However, you still need to build all the packages up to that target package.

The use case you are describing matches a prerelease job provided by the ROS buildfarm. Please see an example graph of dependencies from a ROSCon presentation in 2016: http://www.dirk-thomas.net/slides_roscon2016_ros-buildfarm/2016-10-09_roscon_ros-buildfarm.html#/7/2

The set of packages you describe is not sufficient. In your example a package `foo` depending on `rclcpp` might have other dependencies which must be build too otherwise you would be unable to build / test `foo`.

The correct set for the described use case is:
* **test**: the set of packages selected with `--packages-above rclcpp`

And in order to be able to test these you need to:
* **build**: the same set of packages **plus** all their recursive dependencies

The ROSCon 2019 presentation about `colcon` suggests to use a nested invocation for the second bullet: http://www.dirk-thomas.net/slides_roscon2019_colcon/2019-11-01_roscon_colcon.html#/6/1
* `colcon build --packages-up-to $(colcon list --packages-above rclcpp)`

The `colcon` docs do explicitly describe this use case: https://colcon.readthedocs.io/en/released/user/how-to.html#test-selected-packages-as-well-as-their-dependents

Of course a new option could be added for this use case and use the nested approach as described in the presentation. There are just so many different use cases that it probably is neither feasible nor desirable to add custom options for each of them. Using the nested approach already allows you to satisfy this use case and many more.

**Comment by brawner** [comment]
That's a really cool trick using shell expansion of `--packages-above`. I'll have to remember it for later. However, that command doesn't work in Windows `cmd`, which is the current Windows shell on ci.ros2.org and probably most other Windows build farms nodes. It would work in powershell though. My point though is that using it as an argument on ci.ros2.org would not work on Windows nodes.

The use case I'm trying to describe is how to convince your reviewers that your PR doesn't break other packages. For example, removing a message file from rcl_interfaces (https://github.com/ros2/rcl_interfaces/pull/89). I need to show that any package that recursively depends on rcl_interfaces builds correctly, but ideally that would not be all of ros2.repos (even though in this specific case, it might be). 

You are correct in that a union of the two is not sufficient, but your correction does sufficiently cover the packages that need to be built and tested in order to test a change across a broad set of packages. It is also the minimum set, so it could become the default build/test argument for a test-on-push or test-on-merge style CI system while at the same time minimizing the work load on your CI farm.

If you would welcome a change, I would be happy to contribute it.

**Comment by dirk-thomas** [comment]
> If you would welcome a change, I would be happy to contribute it.

Sure, the only question will be how to name this new option. We can either settle on a name here first or on a to-be-created pull request (where we might have to change the proposed name after we settled on a name).

**Comment by brawner** [comment]
Hmm, it's a tough question because it is not necessarily all packages reachable or connected to a target package, since you wouldn't include a package that just shares a dependency with the target package. So my first instinct of `--packages-connected-to` is probably not appropriate.

Here are my suggestions, not in any particular order.
--packages-above-and-dependencies?
--packages-above-and-depends
--packages-above-and-below
--packages-up-to-and-above
--packages-required-with

**Comment by dirk-thomas** [comment]
I prefer to avoid abbreviations like `depends` - you can always shorten the option when you invoke it - as long as the prefix identifies a unique option.

`above-and-below` / `up-to-and-above` doesn't really describe the actual set correctly. I would say it matches more the set you originally described which doesn't include the dependencies of the above packages.

`required-with` doesn't describes the "above" part of the selection and diverges from the other options by using the term "required" which isn't used / defined anywhere. 

`--packages-above-and-dependencies` sounds good to me.
